event_model_prior:
    dirichlet_process:
        parameters:
            # concentrations -> concentration
            concentration:
                value: 27.15
                estimate: true
                prior:
                    gamma distribution:
                        shape: 1.5
                        scale: 18.1

event_time_prior:
    exponential_distribution:
        # They had t ~ exp(mean = 10) in units of theta-mean/mu generations =
        # 10 (0.005/mu) generations. So if we assume mu = 1, this translates to
        # 10*0.005 = 0.05/mu = 0.05 subs/site
        mean: 0.05

global_comparison_settings:
    # Ploidy is 2 for Mp20 and 0.5 for Cox1. Because ecoevolity is designed for
    # genomic data, there's no great way to deal with this. Leaving it at 1
    # should be fine. Their prior on population size applied directy to Mp20,
    # but will be applied to an "average" for us, but it's a diffuse
    # exponential prior, so the data should enforce the correct scaling of the
    # posterior
    ploidy: 1
    equal_population_sizes: false
    constant_sites_removed: false
    population_name_delimiter: "_"
    population_name_is_prefix: true
    # Genotypes are haploid for Cox1 and diploid for Mp20, so we will need to
    # phase the Mp20 (one haplotype per row) for this to be correct
    genotypes_are_diploid: false
    # Adding parameter settings
    parameters:
        # Their prior on 4*Ne*mu was Exp(mean=0.005). In ecoevolity, we put the
        # prior on Ne*mu, so the mean would be 0.005/4
        population_size:
            value: 0.00125
            estimate: true
            prior:
                exponential_distribution:
                    mean: 0.00125
        root_relative_population_size:
            value: 1.0
            estimate: true
            prior:
                gamma_distribution:
                    shape: 20.0
                    mean: 1.0
        freq_1:
            value: 0.5
            estimate: false

        mutation_rate:
            value: 1.0
            estimate: false

comparisons:
# For ecoevolity, there needs to be one aligment per taxon, and so both Cox1
# and Mp20 need to be concatenated into one nexus file for each taxon.
# Also, for nucleotides to represent the haploid genotype for both loci, we
# should phase Mp20, so it looks something like
#   individual-1a  ACGTACGT
#   individual-1b  ACGT----
#   individual-2a  ACGTACGT
#   individual-2b  ACGT----
# where the first 4 nucs are Mp20 and the last 4 are Cox1. It doesn't matter
# which haplotype of Mp20 the Cox1 seq is "connected" to, because ecoevolity
# assumes everycolumn is an independent, unlinked locus anyway.
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Ammobius2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Ammobius2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Dailhel2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Dailhel2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Dailquadr2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Dailquadr2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Dichomma2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Dichomma2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Erodius2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Erodius2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/EutSand2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/EutSand2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/EutSoilNoD2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/EutSoilNoD2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Graecopachys2_Cox1.nex" 
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Graecopachys2_Mp20.nex" 
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Micrositus2_Cox1.nex" 
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Micrositus2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Pimelia2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Pimelia2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Stenosis2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Stenosis2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Tentyria2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Tentyria2_Mp20.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Zophosis2_Cox1.nex"
-comparison:
    path: "/home/tcm0036/codiv-sanger-bake-off/scripts/dryadData/Papadopolou-et-al/ecoevolity_input_files/all13taxa/Zophosis2_Mp20.nex"
